# Generated by Django 6.0.3 on 2026-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Watches', 'Watches'), ('Beauty', 'Beauty'), ('Furniture', 'Furniture'), ('Groceries', 'Groceries'), ('Sports', 'Sports'), ('Books', 'Books'), ('Toys', 'Toys'), ('Kitchen', 'Kitchen'), ('Accessories', 'Accessories')], max_length=100),
        ),
    ]
