# Generated by Django 6.0.3 on 2026-05-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
