# Generated by Django 6.0.3 on 2026-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Discount in percentage (e.g., 10 for 10%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.FloatField(blank=True, help_text='Calculated price after discount', null=True),
        ),
    ]
