# Generated by Django 6.0.3 on 2026-05-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_discount_percentage_product_off_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='off_price',
        ),
    ]
