# Generated by Django 6.0.3 on 2026-05-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Watches', 'Watches'), ('Beauty', 'Beauty'), ('Furniture', 'Furniture'), ('Groceries', 'Groceries'), ('Sports', 'Sports'), ('Books', 'Books'), ('Toys', 'Toys'), ('Kitchen', 'Kitchen'), ('Accessories', 'Accessories'), ('Poultry', 'Poultry'), ('Branding', 'Branding')], max_length=100),
        ),
    ]
